Roll edk2-basetools back to 0.1.29 (#40)
## Description

The 0.1.39 update breaks the build with the following error:

```
ImportError: cannot import name 'SubTypeGuidSectionClassObject'
  from 'CommonDataClass.FdfClass'
  (D:\a\1\s\MU_BASECORE\BaseTools\Source\Python\CommonDataClass\FdfClass.py)
```

This was missed in the original commit (49eefd0a07) PR gate because PR eval did not perform an actual build.

Roll this back for now until integration changes can be made to pull in the latest edk2-basetools update.

- [ ] Breaking change?
  - Will this change break pre-existing builds or functionality without action being taken?
  **No** - Restores previous functionality

## How This Was Tested

1. Verified CI build breaks with error in description with edk2-basetools 0.1.39
2. Verified CI build succeeds with edk2-basetools 0.1.29

## Integration Instructions

N/A

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>