Roll edk2-basetools back to 0.1.29
The 0.1.39 update breaks the build with the following error:

```
ImportError: cannot import name 'SubTypeGuidSectionClassObject'
  from 'CommonDataClass.FdfClass'
  (D:\a\1\s\MU_BASECORE\BaseTools\Source\Python\CommonDataClass\FdfClass.py)
```

This was missed in the original commit (49eefd0a07) PR gate because
PR eval did not perform an actual build.

Roll this back for now until integration changes can be made to
pull in the latest edk2-basetools update.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>